---
name: Create and publish a Docker image
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - images/**
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changes.outputs.dirs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: changes
        run: |
          find_image_dirs() {
            for dir in $(git diff --name-only HEAD^ HEAD | awk -F'/' '{print $2}' | sort -u); do
              if [ -f "images/$dir/Dockerfile" ]; then
                echo "$dir"
              fi
            done
          }
          dirs=$(find_image_dirs | jq -R . | jq -s . | tr -d '\n')
          echo "Image dirs: $dirs"
          echo "dirs=$dirs" >> $GITHUB_OUTPUT
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.dirs != '[]' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        dir: ${{ fromJson(needs.changes.outputs.dirs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.dir }}
          tags: |
            type=sha,format=short,prefix=
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: images/${{ matrix.dir }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
